name: CICD

on:
  push:
    branches: [main]

jobs:
  code-lint:
    strategy:
      matrix:
        include:
          - service: frontend
          - service: admin
          - service: backend
    uses: ./.github/workflows/lint.yml
    with:
      service: ${{ matrix.service }}

  build:
    needs: [code-lint]
    strategy:
      fail-fast: true
      matrix:
        include:
          - service: backend
            image: store-api
          - service: frontend
            image: store-frontend
          - service: admin
            image: store-admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
